package com.github.niusic.azan

data class AzanZone(val code: String, val name: String)

val azanZones = listOf(
    AzanZone("JHR01", "Johor Bahru, Kota Tinggi, Mersing"),
    AzanZone("JHR02", "Kluang, Pontian"),
    AzanZone("JHR03", "Batu Pahat, Muar, Segamat, Ledang"),
    AzanZone("KDH01", "Kota Setar, Kubang Pasu, Pokok Sena (Daerah Pentadbiran)"),
    AzanZone("KDH02", "Kuala Muda, Yan, Pendang"),
    AzanZone("KDH03", "Padang Terap, Sik"),
    AzanZone("KDH04", "Baling"),
    AzanZone("KDH05", "Bandar Baharu, Kulim"),
    AzanZone("KDH06", "Langkawi"),
    AzanZone("KDH07", "Puncak Gunung Jerai"),
    AzanZone("KTN01", "Bachok, Kota Bharu, Machang, Pasir Mas, Pasir Puteh, Tanah Merah, Tumpat, Kuala Krai, Mukim Chiku"),
    AzanZone("KTN03", "Gua Musang (Mukim Galas Dan Bertam), Jeli"),
    AzanZone("MLK01", "Seluruh Negeri Melaka"),
    AzanZone("NSN01", "Tampin, Rembau"),
    AzanZone("NSN02", "Jempol, Kuala Pilah"),
    AzanZone("NSN03", "Port Dickson, Seremban, Kuala Klawang"),
    AzanZone("PHG01", "Pulau Tioman"),
    AzanZone("PHG02", "Kuantan, Pekan, Rompin, Muadzam Shah"),
    AzanZone("PHG03", "Jerantut, Temerloh, Maran, Bera, Chenor, Jengka"),
    AzanZone("PHG04", "Bentong, Lipis, Raub"),
    AzanZone("PHG05", "Genting Sempah, Janda Baik, Bukit Tinggi"),
    AzanZone("PHG06", "Cameron Highlands, Genting Higlands, Bukit Fraser"),
    AzanZone("PLS01", "Seluruh Negeri Perlis"),
    AzanZone("PNG01", "Seluruh Negeri Pulau Pinang"),
    AzanZone("PRK01", "Tapah, Slim River, Tanjung Malim"),
    AzanZone("PRK02", "Kuala Kangsar, Sg. Siput (Daerah Kecil), Ipoh, Batu Gajah, Kampar"),
    AzanZone("PRK03", "Lenggong, Pengkalan Hulu, Grik"),
    AzanZone("PRK04", "Temengor, Belum"),
    AzanZone("PRK05", "Kg. Gajah, Teluk Intan, Bagan Datuk, Seri Iskandar, Beruas, Parit, Lumut, Sitiawan, Pulau Pangkor"),
    AzanZone("PRK06", "Selama, Taiping, Bagan Serai, Parit Buntar"),
    AzanZone("PRK07", "Bukit Larut"),
    AzanZone("SBH01", "Bahagian Sandakan (Timur): Tomanggong, Sukau, Samawang, Kota Kinabatangan, Bukit Garam, Sandakan, Beluran"),
    AzanZone("SBH02", "Bahagian Sandakan (Barat): Pinangah, Terusan, Beluran, Telupid, Beluran"),
    AzanZone("SBH03", "Bahagian Tawau (Timur): Lahad Datu, Kunak, Silabukan, Tungku, Sahabat, Semporna"),
    AzanZone("SBH04", "Bahagian Tawau (Barat): Tawau, Balung, Merotai, Kalabakan"),
    AzanZone("SBH05", "Bahagian Kudat: Kudat, Kota Marudu, Pitas, Pulau Banggi"),
    AzanZone("SBH06", "Bahagian Pantai Barat: Ranau, Kota Belud, Tuaran, Penampang, Kota Kinabalu, Putatan, Papar"),
    AzanZone("SBH07", "Bahagian Pedalaman (Atas): Beaufort, Kuala Penyu, Sipitang, Tenom, Long Pa Sia, Membakut, Weston"),
    AzanZone("SBH08", "Bahagian Pedalaman (Bawah): Nabawan, Pensiangan, Sopulut, Tambunan, Keningau"),
    AzanZone("SBH09", "Bahagian Pantai Barat: Ranau, Kota Belud, Tuaran, Penampang, Kota Kinabalu, Putatan, Papar"),
    AzanZone("SGR01", "Gombak, Petaling, Sepang, Hulu Langat, Hulu Selangor, S.Alam"),
    AzanZone("SGR02", "Sabak Bernam, Kuala Selangor, Klang, Kuala Langat"),
    AzanZone("SGR03", "Bukit Fraser, Genting Highlands, Janda Baik"),
    AzanZone("SWK01", "Lundu, Sematan"),
    AzanZone("SWK02", "Bau, Kuching, Serian, Simunjan, Samarahan"),
    AzanZone("SWK03", "Sri Aman, Engkilili, Lubok Antu, Betong, Saratok, Roban, Kabong"),
    AzanZone("SWK04", "Igan, Kanowit, Sibu, Dalat, Oya"),
    AzanZone("SWK05", "Belawai, Matu, Daro, Sarikei, Julau, Bintangor, Nyabor"),
    AzanZone("SWK06", "Tatau, Belaga, Kapit, Song, Kanowit, Sebauh"),
    AzanZone("SWK07", "Bintulu"),
    AzanZone("SWK08", "Miri, Marudi, Niah, Beluru, Sibuti, Lambir"),
    AzanZone("SWK09", "Limbang, Lawas, Sundar, Terusan"),
    AzanZone("TRG01", "Kuala Terengganu, Marang, Kuala Nerus"),
    AzanZone("TRG02", "Besut, Setiu"),
    AzanZone("TRG03", "Hulu Terengganu"),
    AzanZone("TRG04", "Dungun, Kemaman"),
    AzanZone("WLY01", "Kuala Lumpur, Putrajaya"),
    AzanZone("WLY02", "Labuan")
)

